Red []

#include %kernel.red
#include %io.red
#include %body.red
#include %string.red
#include %word.red
#include %integer.red
#include %series.red
#include %bitset.red
#include %map.red
#include %tuple.red
#include %keyword.red
#include %pair.red
#include %date.red
#include %time.red
#include %file.red
#include %url.red
#include %enum.red
#include %sets.red
#include %iteration.red
#include %sigil.red
#include %error.red
#include %logger.red
#include %math.red
